<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCMGAxXg\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCMGAxXg/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCMGAxXg.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerCMGAxXg\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerCMGAxXg\srcProdProjectContainer(array(
    'container.build_hash' => 'CMGAxXg',
    'container.build_id' => 'fe60fc33',
    'container.build_time' => 1542639972,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCMGAxXg');
