<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUtW3hIX\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUtW3hIX/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUtW3hIX.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerUtW3hIX\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerUtW3hIX\srcProdProjectContainer(array(
    'container.build_hash' => 'UtW3hIX',
    'container.build_id' => 'a145c620',
    'container.build_time' => 1540922017,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUtW3hIX');
