<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDOtrQrV\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDOtrQrV/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDOtrQrV.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDOtrQrV\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerDOtrQrV\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'DOtrQrV',
    'container.build_id' => '86a68942',
    'container.build_time' => 1541695116,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDOtrQrV');
