<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDYLarQF\srcDevProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDYLarQF/srcDevProjectContainer.php') {
    touch(__DIR__.'/ContainerDYLarQF.legacy');

    return;
}

if (!\class_exists(srcDevProjectContainer::class, false)) {
    \class_alias(\ContainerDYLarQF\srcDevProjectContainer::class, srcDevProjectContainer::class, false);
}

return new \ContainerDYLarQF\srcDevProjectContainer(array(
    'container.build_hash' => 'DYLarQF',
    'container.build_id' => 'db43d5e2',
    'container.build_time' => 1542639757,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDYLarQF');
