<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBeuqn1h\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBeuqn1h/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBeuqn1h.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBeuqn1h\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerBeuqn1h\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Beuqn1h',
    'container.build_id' => '1ab03b59',
    'container.build_time' => 1542277997,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBeuqn1h');
