<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container196bqb6\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container196bqb6/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container196bqb6.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container196bqb6\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container196bqb6\srcDevDebugProjectContainer(array(
    'container.build_hash' => '196bqb6',
    'container.build_id' => '8f3edcd8',
    'container.build_time' => 1541434618,
), __DIR__.\DIRECTORY_SEPARATOR.'Container196bqb6');
