<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserCache extends \App\Entity\UserCache implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\UserCache' . "\0" . 'idCache', '' . "\0" . 'App\\Entity\\UserCache' . "\0" . 'score', '' . "\0" . 'App\\Entity\\UserCache' . "\0" . 'difficulty', '' . "\0" . 'App\\Entity\\UserCache' . "\0" . 'time', '' . "\0" . 'App\\Entity\\UserCache' . "\0" . 'lang1', '' . "\0" . 'App\\Entity\\UserCache' . "\0" . 'lang2', '' . "\0" . 'App\\Entity\\UserCache' . "\0" . 'idUser'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\UserCache' . "\0" . 'idCache', '' . "\0" . 'App\\Entity\\UserCache' . "\0" . 'score', '' . "\0" . 'App\\Entity\\UserCache' . "\0" . 'difficulty', '' . "\0" . 'App\\Entity\\UserCache' . "\0" . 'time', '' . "\0" . 'App\\Entity\\UserCache' . "\0" . 'lang1', '' . "\0" . 'App\\Entity\\UserCache' . "\0" . 'lang2', '' . "\0" . 'App\\Entity\\UserCache' . "\0" . 'idUser'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UserCache $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdCache(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdCache();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCache', []);

        return parent::getIdCache();
    }

    /**
     * {@inheritDoc}
     */
    public function getScore(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScore', []);

        return parent::getScore();
    }

    /**
     * {@inheritDoc}
     */
    public function setScore(int $score): \App\Entity\UserCache
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScore', [$score]);

        return parent::setScore($score);
    }

    /**
     * {@inheritDoc}
     */
    public function getDifficulty(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDifficulty', []);

        return parent::getDifficulty();
    }

    /**
     * {@inheritDoc}
     */
    public function setDifficulty(string $difficulty): \App\Entity\UserCache
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDifficulty', [$difficulty]);

        return parent::setDifficulty($difficulty);
    }

    /**
     * {@inheritDoc}
     */
    public function getTime(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTime', []);

        return parent::getTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setTime(int $time): \App\Entity\UserCache
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTime', [$time]);

        return parent::setTime($time);
    }

    /**
     * {@inheritDoc}
     */
    public function getLang1(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLang1', []);

        return parent::getLang1();
    }

    /**
     * {@inheritDoc}
     */
    public function setLang1(string $lang1): \App\Entity\UserCache
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLang1', [$lang1]);

        return parent::setLang1($lang1);
    }

    /**
     * {@inheritDoc}
     */
    public function getLang2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLang2', []);

        return parent::getLang2();
    }

    /**
     * {@inheritDoc}
     */
    public function setLang2(string $lang2): \App\Entity\UserCache
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLang2', [$lang2]);

        return parent::setLang2($lang2);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUser(): ?\App\Entity\UserData
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUser', []);

        return parent::getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUser(?\App\Entity\UserData $idUser): \App\Entity\UserCache
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUser', [$idUser]);

        return parent::setIdUser($idUser);
    }

}
